"""initial schema

Revision ID: 847f8fffb5ac
Revises: 
Create Date: 2026-09-15 21:25:51.679041
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '847f8fffb5ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_categories',
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('default_shelf_life_days', sa.Float(), nullable=True),
    sa.Column('ideal_temp_min_c', sa.Float(), nullable=True),
    sa.Column('ideal_temp_max_c', sa.Float(), nullable=True),
    sa.Column('ideal_humidity_min_pct', sa.Float(), nullable=True),
    sa.Column('ideal_humidity_max_pct', sa.Float(), nullable=True),
    sa.Column('perishability', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_categories'))
    )
    with op.batch_alter_table('food_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_categories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_categories_slug'), ['slug'], unique=True)

    op.create_table('roles',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('oauth_provider', sa.String(length=40), nullable=True),
    sa.Column('oauth_subject', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_oauth_subject'), ['oauth_subject'], unique=False)
        batch_op.create_index('ix_users_role_active', ['role_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_role', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=300), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_action_created', ['action', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index('ix_audit_logs_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('food_products',
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('default_unit', sa.String(length=20), nullable=False),
    sa.Column('shelf_life_days', sa.Float(), nullable=True),
    sa.Column('default_packaging', sa.String(length=40), nullable=True),
    sa.Column('storage_instructions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['food_categories.id'], name=op.f('fk_food_products_category_id_food_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_food_products_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_products')),
    sa.UniqueConstraint('sku', name='uq_food_products_sku')
    )
    with op.batch_alter_table('food_products', schema=None) as batch_op:
        batch_op.create_index('ix_food_products_category_active', ['category_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_products_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_products_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_products_sku'), ['sku'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('jti', name='uq_refresh_tokens_jti')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_refresh_tokens_user_revoked', ['user_id', 'revoked'], unique=False)

    op.create_table('reports',
    sa.Column('report_type', sa.String(length=40), nullable=False),
    sa.Column('report_format', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('generation_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_reports_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)
        batch_op.create_index('ix_reports_type_created', ['report_type', 'created_at'], unique=False)

    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('organisation', sa.String(length=160), nullable=True),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('default_storage_location', sa.String(length=160), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('notify_in_app', sa.Boolean(), nullable=False),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles'))
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('food_batches',
    sa.Column('batch_number', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('storage_date', sa.Date(), nullable=True),
    sa.Column('expected_expiry_date', sa.Date(), nullable=True),
    sa.Column('predicted_expiry_date', sa.Date(), nullable=True),
    sa.Column('packaging_type', sa.String(length=40), nullable=True),
    sa.Column('storage_location', sa.String(length=160), nullable=True),
    sa.Column('supplier', sa.String(length=160), nullable=True),
    sa.Column('cost_per_unit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('current_freshness_score', sa.Float(), nullable=True),
    sa.Column('current_freshness_category', sa.String(length=24), nullable=True),
    sa.Column('remaining_shelf_life_days', sa.Float(), nullable=True),
    sa.Column('last_assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_food_batches_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['food_products.id'], name=op.f('fk_food_batches_product_id_food_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_batches')),
    sa.UniqueConstraint('batch_number', name='uq_food_batches_batch_number')
    )
    with op.batch_alter_table('food_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_batches_batch_number'), ['batch_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_batches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_batches_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_batches_current_freshness_category'), ['current_freshness_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_batches_current_freshness_score'), ['current_freshness_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_batches_expected_expiry_date'), ['expected_expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_batches_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index('ix_food_batches_location', ['storage_location'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_batches_predicted_expiry_date'), ['predicted_expiry_date'], unique=False)
        batch_op.create_index('ix_food_batches_product_created', ['product_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_batches_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_batches_purchase_date'), ['purchase_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_batches_remaining_shelf_life_days'), ['remaining_shelf_life_days'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_batches_status'), ['status'], unique=False)
        batch_op.create_index('ix_food_batches_status_expiry', ['status', 'expected_expiry_date'], unique=False)

    op.create_table('alerts',
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('triggered_by_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['food_batches.id'], name=op.f('fk_alerts_batch_id_food_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_alerts_resolved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], name=op.f('fk_alerts_triggered_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index('ix_alerts_batch_created', ['batch_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_resolved'), ['resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index('ix_alerts_severity_resolved', ['severity', 'resolved'], unique=False)
        batch_op.create_index('ix_alerts_type_created', ['alert_type', 'created_at'], unique=False)

    op.create_table('food_images',
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('overlay_storage_key', sa.String(length=500), nullable=True),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('is_analyzed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['food_batches.id'], name=op.f('fk_food_images_batch_id_food_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_food_images_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_images'))
    )
    with op.batch_alter_table('food_images', schema=None) as batch_op:
        batch_op.create_index('ix_food_images_batch_created', ['batch_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_images_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_images_checksum_sha256'), ['checksum_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_images_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_images_is_analyzed'), ['is_analyzed'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_images_uploaded_by_id'), ['uploaded_by_id'], unique=False)

    op.create_table('inventory_items',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('storage_location', sa.String(length=160), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('storage_date', sa.Date(), nullable=True),
    sa.Column('expected_expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('rotation_priority', sa.Float(), nullable=True),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('discarded', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['food_batches.id'], name=op.f('fk_inventory_items_batch_id_food_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_inventory_items_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_items'))
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_items_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_inventory_items_expiry', ['expected_expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_inventory_items_owner_status', ['owner_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_rotation_priority'), ['rotation_priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_storage_location'), ['storage_location'], unique=False)

    op.create_table('storage_conditions',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=160), nullable=True),
    sa.Column('zone', sa.String(length=80), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('air_circulation', sa.String(length=20), nullable=True),
    sa.Column('light_exposure', sa.String(length=20), nullable=True),
    sa.Column('storage_duration_days', sa.Float(), nullable=True),
    sa.Column('required_temp_min_c', sa.Float(), nullable=True),
    sa.Column('required_temp_max_c', sa.Float(), nullable=True),
    sa.Column('required_humidity_min_pct', sa.Float(), nullable=True),
    sa.Column('required_humidity_max_pct', sa.Float(), nullable=True),
    sa.Column('compliance_status', sa.String(length=20), nullable=False),
    sa.Column('storage_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('violations', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['food_batches.id'], name=op.f('fk_storage_conditions_batch_id_food_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storage_conditions'))
    )
    with op.batch_alter_table('storage_conditions', schema=None) as batch_op:
        batch_op.create_index('ix_storage_conditions_batch_active', ['batch_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_conditions_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index('ix_storage_conditions_compliance', ['compliance_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_conditions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_conditions_location_name'), ['location_name'], unique=False)

    op.create_table('freshness_assessments',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('assessed_by_id', sa.Integer(), nullable=True),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('freshness_category', sa.String(length=24), nullable=False),
    sa.Column('freshness_probability', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('spoilage_probability', sa.Float(), nullable=True),
    sa.Column('overall_health_score', sa.Float(), nullable=True),
    sa.Column('visual_score', sa.Float(), nullable=True),
    sa.Column('storage_score', sa.Float(), nullable=True),
    sa.Column('shelf_life_score', sa.Float(), nullable=True),
    sa.Column('product_age_score', sa.Float(), nullable=True),
    sa.Column('weights_used', sa.JSON(), nullable=True),
    sa.Column('model_kind', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('visual_features', sa.JSON(), nullable=True),
    sa.Column('class_probabilities', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('detected_indicators', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('input_temperature_c', sa.Float(), nullable=True),
    sa.Column('input_humidity_pct', sa.Float(), nullable=True),
    sa.Column('input_packaging', sa.String(length=40), nullable=True),
    sa.Column('input_storage_duration_days', sa.Float(), nullable=True),
    sa.Column('input_product_age_days', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessed_by_id'], ['users.id'], name=op.f('fk_freshness_assessments_assessed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['batch_id'], ['food_batches.id'], name=op.f('fk_freshness_assessments_batch_id_food_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['food_images.id'], name=op.f('fk_freshness_assessments_image_id_food_images'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_freshness_assessments'))
    )
    with op.batch_alter_table('freshness_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_freshness_assessments_assessed_by_id'), ['assessed_by_id'], unique=False)
        batch_op.create_index('ix_freshness_assessments_batch_created', ['batch_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_freshness_assessments_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index('ix_freshness_assessments_category', ['freshness_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_freshness_assessments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_freshness_assessments_freshness_score'), ['freshness_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_freshness_assessments_image_id'), ['image_id'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_notifications_alert_id_alerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index('ix_notifications_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'is_read'], unique=False)

    op.create_table('storage_readings',
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('storage_condition_id', sa.Integer(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('location_name', sa.String(length=160), nullable=True),
    sa.Column('sensor_id', sa.String(length=80), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('air_circulation', sa.String(length=20), nullable=True),
    sa.Column('light_exposure', sa.String(length=20), nullable=True),
    sa.Column('co2_ppm', sa.Float(), nullable=True),
    sa.Column('compliance_status', sa.String(length=20), nullable=True),
    sa.Column('is_violation', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['food_batches.id'], name=op.f('fk_storage_readings_batch_id_food_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_storage_readings_recorded_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['storage_condition_id'], ['storage_conditions.id'], name=op.f('fk_storage_readings_storage_condition_id_storage_conditions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storage_readings'))
    )
    with op.batch_alter_table('storage_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storage_readings_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index('ix_storage_readings_batch_recorded', ['batch_id', 'recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_readings_compliance_status'), ['compliance_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_readings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_readings_is_violation'), ['is_violation'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_readings_location_name'), ['location_name'], unique=False)
        batch_op.create_index('ix_storage_readings_location_recorded', ['location_name', 'recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_readings_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_readings_sensor_id'), ['sensor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_readings_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_readings_storage_condition_id'), ['storage_condition_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('rule_id', sa.String(length=80), nullable=True),
    sa.Column('action_label', sa.String(length=120), nullable=True),
    sa.Column('expected_impact', sa.String(length=255), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['freshness_assessments.id'], name=op.f('fk_recommendations_assessment_id_freshness_assessments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['batch_id'], ['food_batches.id'], name=op.f('fk_recommendations_batch_id_food_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index('ix_recommendations_batch_type', ['batch_id', 'recommendation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_recommendations_priority', ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_recommendation_type'), ['recommendation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_rule_id'), ['rule_id'], unique=False)

    op.create_table('shelf_life_predictions',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('predicted_by_id', sa.Integer(), nullable=True),
    sa.Column('remaining_shelf_life_days', sa.Float(), nullable=False),
    sa.Column('predicted_expiry_date', sa.Date(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('lower_bound_days', sa.Float(), nullable=True),
    sa.Column('upper_bound_days', sa.Float(), nullable=True),
    sa.Column('model_kind', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('factors', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['freshness_assessments.id'], name=op.f('fk_shelf_life_predictions_assessment_id_freshness_assessments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['batch_id'], ['food_batches.id'], name=op.f('fk_shelf_life_predictions_batch_id_food_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['predicted_by_id'], ['users.id'], name=op.f('fk_shelf_life_predictions_predicted_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shelf_life_predictions'))
    )
    with op.batch_alter_table('shelf_life_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelf_life_predictions_assessment_id'), ['assessment_id'], unique=True)
        batch_op.create_index('ix_shelf_life_predictions_batch_created', ['batch_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shelf_life_predictions_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shelf_life_predictions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shelf_life_predictions_predicted_expiry_date'), ['predicted_expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shelf_life_predictions_remaining_shelf_life_days'), ['remaining_shelf_life_days'], unique=False)
        batch_op.create_index('ix_shelf_life_predictions_risk', ['risk_level'], unique=False)

    op.create_table('spoilage_indicators',
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('indicator_type', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('affected_area_ratio', sa.Float(), nullable=True),
    sa.Column('detected', sa.Boolean(), nullable=False),
    sa.Column('regions', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detector', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['freshness_assessments.id'], name=op.f('fk_spoilage_indicators_assessment_id_freshness_assessments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spoilage_indicators'))
    )
    with op.batch_alter_table('spoilage_indicators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spoilage_indicators_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spoilage_indicators_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_spoilage_indicators_type', ['indicator_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spoilage_indicators', schema=None) as batch_op:
        batch_op.drop_index('ix_spoilage_indicators_type')
        batch_op.drop_index(batch_op.f('ix_spoilage_indicators_created_at'))
        batch_op.drop_index(batch_op.f('ix_spoilage_indicators_assessment_id'))

    op.drop_table('spoilage_indicators')
    with op.batch_alter_table('shelf_life_predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_shelf_life_predictions_risk')
        batch_op.drop_index(batch_op.f('ix_shelf_life_predictions_remaining_shelf_life_days'))
        batch_op.drop_index(batch_op.f('ix_shelf_life_predictions_predicted_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_shelf_life_predictions_created_at'))
        batch_op.drop_index(batch_op.f('ix_shelf_life_predictions_batch_id'))
        batch_op.drop_index('ix_shelf_life_predictions_batch_created')
        batch_op.drop_index(batch_op.f('ix_shelf_life_predictions_assessment_id'))

    op.drop_table('shelf_life_predictions')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_rule_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_recommendation_type'))
        batch_op.drop_index('ix_recommendations_priority')
        batch_op.drop_index(batch_op.f('ix_recommendations_created_at'))
        batch_op.drop_index('ix_recommendations_batch_type')
        batch_op.drop_index(batch_op.f('ix_recommendations_batch_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_assessment_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('storage_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storage_readings_storage_condition_id'))
        batch_op.drop_index(batch_op.f('ix_storage_readings_source'))
        batch_op.drop_index(batch_op.f('ix_storage_readings_sensor_id'))
        batch_op.drop_index(batch_op.f('ix_storage_readings_recorded_at'))
        batch_op.drop_index('ix_storage_readings_location_recorded')
        batch_op.drop_index(batch_op.f('ix_storage_readings_location_name'))
        batch_op.drop_index(batch_op.f('ix_storage_readings_is_violation'))
        batch_op.drop_index(batch_op.f('ix_storage_readings_created_at'))
        batch_op.drop_index(batch_op.f('ix_storage_readings_compliance_status'))
        batch_op.drop_index('ix_storage_readings_batch_recorded')
        batch_op.drop_index(batch_op.f('ix_storage_readings_batch_id'))

    op.drop_table('storage_readings')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index('ix_notifications_user_created')
        batch_op.drop_index(batch_op.f('ix_notifications_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_alert_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('freshness_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_freshness_assessments_image_id'))
        batch_op.drop_index(batch_op.f('ix_freshness_assessments_freshness_score'))
        batch_op.drop_index(batch_op.f('ix_freshness_assessments_created_at'))
        batch_op.drop_index('ix_freshness_assessments_category')
        batch_op.drop_index(batch_op.f('ix_freshness_assessments_batch_id'))
        batch_op.drop_index('ix_freshness_assessments_batch_created')
        batch_op.drop_index(batch_op.f('ix_freshness_assessments_assessed_by_id'))

    op.drop_table('freshness_assessments')
    with op.batch_alter_table('storage_conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storage_conditions_location_name'))
        batch_op.drop_index(batch_op.f('ix_storage_conditions_created_at'))
        batch_op.drop_index('ix_storage_conditions_compliance')
        batch_op.drop_index(batch_op.f('ix_storage_conditions_batch_id'))
        batch_op.drop_index('ix_storage_conditions_batch_active')

    op.drop_table('storage_conditions')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_storage_location'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_status'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_rotation_priority'))
        batch_op.drop_index('ix_inventory_items_owner_status')
        batch_op.drop_index(batch_op.f('ix_inventory_items_owner_id'))
        batch_op.drop_index('ix_inventory_items_expiry')
        batch_op.drop_index(batch_op.f('ix_inventory_items_created_at'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_batch_id'))

    op.drop_table('inventory_items')
    with op.batch_alter_table('food_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_images_uploaded_by_id'))
        batch_op.drop_index(batch_op.f('ix_food_images_is_analyzed'))
        batch_op.drop_index(batch_op.f('ix_food_images_created_at'))
        batch_op.drop_index(batch_op.f('ix_food_images_checksum_sha256'))
        batch_op.drop_index(batch_op.f('ix_food_images_batch_id'))
        batch_op.drop_index('ix_food_images_batch_created')

    op.drop_table('food_images')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_alerts_type_created')
        batch_op.drop_index('ix_alerts_severity_resolved')
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_resolved'))
        batch_op.drop_index(batch_op.f('ix_alerts_is_read'))
        batch_op.drop_index(batch_op.f('ix_alerts_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_batch_id'))
        batch_op.drop_index('ix_alerts_batch_created')
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))

    op.drop_table('alerts')
    with op.batch_alter_table('food_batches', schema=None) as batch_op:
        batch_op.drop_index('ix_food_batches_status_expiry')
        batch_op.drop_index(batch_op.f('ix_food_batches_status'))
        batch_op.drop_index(batch_op.f('ix_food_batches_remaining_shelf_life_days'))
        batch_op.drop_index(batch_op.f('ix_food_batches_purchase_date'))
        batch_op.drop_index(batch_op.f('ix_food_batches_product_id'))
        batch_op.drop_index('ix_food_batches_product_created')
        batch_op.drop_index(batch_op.f('ix_food_batches_predicted_expiry_date'))
        batch_op.drop_index('ix_food_batches_location')
        batch_op.drop_index(batch_op.f('ix_food_batches_is_archived'))
        batch_op.drop_index(batch_op.f('ix_food_batches_expected_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_food_batches_current_freshness_score'))
        batch_op.drop_index(batch_op.f('ix_food_batches_current_freshness_category'))
        batch_op.drop_index(batch_op.f('ix_food_batches_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_food_batches_created_at'))
        batch_op.drop_index(batch_op.f('ix_food_batches_batch_number'))

    op.drop_table('food_batches')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_created_at'))

    op.drop_table('user_profiles')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_type_created')
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_reports_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))

    op.drop_table('reports')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_refresh_tokens_user_revoked')
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_created_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('food_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_products_sku'))
        batch_op.drop_index(batch_op.f('ix_food_products_name'))
        batch_op.drop_index(batch_op.f('ix_food_products_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_food_products_created_at'))
        batch_op.drop_index(batch_op.f('ix_food_products_category_id'))
        batch_op.drop_index('ix_food_products_category_active')

    op.drop_table('food_products')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index('ix_audit_logs_user_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index('ix_audit_logs_action_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index('ix_users_role_active')
        batch_op.drop_index(batch_op.f('ix_users_oauth_subject'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_created_at'))

    op.drop_table('roles')
    with op.batch_alter_table('food_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_food_categories_created_at'))

    op.drop_table('food_categories')
    # ### end Alembic commands ###