"""initial_food_monitoring_schema

Revision ID: b92fd8490f37
Revises: 
Create Date: 2026-09-06 11:40:11.156545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b92fd8490f37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('Fruits', 'Vegetables', 'Dairy', 'Meat & Poultry', 'Seafood', 'Bakery', 'Packaged Foods', 'Beverages', name='food_category'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_items_created_at'), 'food_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_food_items_name'), 'food_items', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('Consumer', 'Retail Manager', 'Warehouse Operator', 'Food Quality Inspector', 'Administrator', name='user_role'), server_default='Consumer', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('food_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_item_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('storage_location', sa.String(length=255), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_item_id', 'batch_number', name='uq_food_batches_item_batch_number')
    )
    op.create_index(op.f('ix_food_batches_batch_number'), 'food_batches', ['batch_number'], unique=False)
    op.create_index(op.f('ix_food_batches_created_at'), 'food_batches', ['created_at'], unique=False)
    op.create_index(op.f('ix_food_batches_expiry_date'), 'food_batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_food_batches_food_item_id'), 'food_batches', ['food_item_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('Freshness Report', 'Shelf-Life Report', 'Inventory Quality Report', 'Waste Reduction Report', 'Storage Compliance Report', name='report_type'), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('record_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_generated_at'), 'reports', ['generated_at'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_batch_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('Freshness', 'Shelf Life', 'Spoilage', 'Storage', 'Inventory', name='alert_category'), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_batch_id'], ['food_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_food_batch_id'), 'alerts', ['food_batch_id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('freshness_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_batch_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('freshness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('freshness_category', sa.Enum('Fresh', 'Good', 'Acceptable', 'Near Spoilage', 'Spoiled', name='freshness_category'), nullable=True),
    sa.Column('spoilage_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('analysis_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_batch_id'], ['food_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freshness_analyses_analyzed_at'), 'freshness_analyses', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_freshness_analyses_food_batch_id'), 'freshness_analyses', ['food_batch_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_batch_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.Enum('Storage', 'Consumption', 'Inventory Rotation', 'Waste Reduction', 'Quality Improvement', name='recommendation_type'), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='Pending', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_batch_id'], ['food_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_created_at'), 'recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendations_food_batch_id'), 'recommendations', ['food_batch_id'], unique=False)
    op.create_table('shelf_life_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_batch_id', sa.Integer(), nullable=False),
    sa.Column('remaining_days', sa.Integer(), nullable=True),
    sa.Column('predicted_expiry_date', sa.Date(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('humidity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('packaging', sa.String(length=100), nullable=True),
    sa.Column('storage_duration', sa.Integer(), nullable=True),
    sa.Column('prediction_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_batch_id'], ['food_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelf_life_predictions_food_batch_id'), 'shelf_life_predictions', ['food_batch_id'], unique=False)
    op.create_index(op.f('ix_shelf_life_predictions_predicted_at'), 'shelf_life_predictions', ['predicted_at'], unique=False)
    op.create_table('storage_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_batch_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('humidity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('air_circulation', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('light_level', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_batch_id'], ['food_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_conditions_food_batch_id'), 'storage_conditions', ['food_batch_id'], unique=False)
    op.create_index(op.f('ix_storage_conditions_recorded_at'), 'storage_conditions', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_conditions_recorded_at'), table_name='storage_conditions')
    op.drop_index(op.f('ix_storage_conditions_food_batch_id'), table_name='storage_conditions')
    op.drop_table('storage_conditions')
    op.drop_index(op.f('ix_shelf_life_predictions_predicted_at'), table_name='shelf_life_predictions')
    op.drop_index(op.f('ix_shelf_life_predictions_food_batch_id'), table_name='shelf_life_predictions')
    op.drop_table('shelf_life_predictions')
    op.drop_index(op.f('ix_recommendations_food_batch_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_created_at'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_freshness_analyses_food_batch_id'), table_name='freshness_analyses')
    op.drop_index(op.f('ix_freshness_analyses_analyzed_at'), table_name='freshness_analyses')
    op.drop_table('freshness_analyses')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_food_batch_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_generated_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_food_batches_food_item_id'), table_name='food_batches')
    op.drop_index(op.f('ix_food_batches_expiry_date'), table_name='food_batches')
    op.drop_index(op.f('ix_food_batches_created_at'), table_name='food_batches')
    op.drop_index(op.f('ix_food_batches_batch_number'), table_name='food_batches')
    op.drop_table('food_batches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_food_items_name'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_created_at'), table_name='food_items')
    op.drop_table('food_items')
    # ### end Alembic commands ###
