import React, { useState, useEffect } from "react";
import {
  FileBarChart,
  Download,
  Plus,
  Calendar,
  CheckCircle2,
  FileText,
  Filter,
  Sparkles,
  ArrowDownToLine,
  Printer
} from "lucide-react";
import { Modal } from "../components/UI/Modal";
import { Toast } from "../components/UI/Toast";
import { api } from "../services/api";

export const REPORT_TYPES = [
  "All",
  "Freshness Report",
  "Shelf-Life Report",
  "Inventory Quality Report",
  "Waste Reduction Report",
  "Storage Compliance Report",
];

export const Reports = () => {
  const [reports, setReports] = useState([]);
  const [filterType, setFilterType] = useState("All");
  const [isGenerateModalOpen, setIsGenerateModalOpen] = useState(false);
  const [isViewModalOpen, setIsViewModalOpen] = useState(false);
  const [selectedReport, setSelectedReport] = useState(null);
  const [toastMessage, setToastMessage] = useState(null);

  const [formType, setFormType] = useState("Freshness Report");
  const [formTitle, setFormTitle] = useState("");

  const fetchReports = async () => {
    try {
      const data = await api.getReports(filterType);
      setReports(data);
    } catch (e) {
      console.error(e);
    }
  };

  useEffect(() => {
    fetchReports();
  }, [filterType]);

  const handleGenerate = async (e) => {
    e.preventDefault();
    try {
      await api.generateReport({
        report_type: formType,
        title: formTitle || undefined,
        generated_by: "Food Quality Inspector",
      });
      setIsGenerateModalOpen(false);
      setToastMessage({ type: "success", text: "New report generated successfully!" });
      fetchReports();
    } catch (e) {
      setToastMessage({ type: "error", text: "Failed to generate report." });
    }
  };

  const handleDownloadDemo = (report) => {
    // Generate simple text blob as downloadable audit report for the demo
    const blobContent = `
=====================================================
FOOD FRESHNESS MONITORING PLATFORM - AUDIT REPORT
=====================================================
Title: ${report.title}
Report Type: ${report.report_type}
Date: ${report.created_at}
Generated By: ${report.generated_by}
Status: Verified Enterprise Audit Standard

Summary:
${report.summary}

Telemetry & Compliance Metrics:
${JSON.stringify(report.data, null, 2)}

Verified by FreshGuard AI Quality Assurance Model v1.0
=====================================================
    `.trim();

    const blob = new Blob([blobContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${report.title.replace(/\s+/g, "_")}.txt`;
    a.click();
    URL.revokeObjectURL(url);

    setToastMessage({ type: "success", text: `Downloading ${report.title}...` });
  };

  return (
    <div className="space-y-6 pb-12 max-w-5xl mx-auto">
      {toastMessage && (
        <Toast
          message={toastMessage.text}
          type={toastMessage.type}
          onClose={() => setToastMessage(null)}
        />
      )}

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-emerald-400 text-xs font-bold uppercase tracking-wider mb-1">
            <Sparkles className="w-4 h-4" /> Compliance & Quality Verification
          </div>
          <h2 className="text-2xl font-extrabold text-white tracking-tight flex items-center gap-2">
            <FileBarChart className="w-6 h-6 text-emerald-400" />
            Compliance & Quality Reports
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Export certified freshness audits, shelf-life forecasts, and storage telemetry for regulatory standards.
          </p>
        </div>

        <button
          onClick={() => {
            setFormTitle(`Automated Quality Audit (${new Date().toLocaleDateString()})`);
            setIsGenerateModalOpen(true);
          }}
          className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-600 hover:to-teal-600 text-white font-bold text-xs shadow-lg shadow-emerald-500/25 transition-all transform active:scale-95"
        >
          <Plus className="w-4 h-4" />
          <span>Generate New Report</span>
        </button>
      </div>

      {/* Filter Tabs */}
      <div className="flex flex-wrap items-center gap-1.5 bg-slate-800/80 border border-slate-700/80 p-1.5 rounded-xl">
        {REPORT_TYPES.map((t) => (
          <button
            key={t}
            onClick={() => setFilterType(t)}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors ${
              filterType === t
                ? "bg-emerald-500 text-white shadow"
                : "text-slate-400 hover:text-white"
            }`}
          >
            {t}
          </button>
        ))}
      </div>

      {/* Reports List */}
      <div className="space-y-4">
        {reports.map((report) => (
          <div
            key={report.id}
            className="glass-card rounded-2xl p-5 border border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-4"
          >
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-xl bg-slate-800 border border-slate-700 flex items-center justify-center flex-shrink-0 text-emerald-400 shadow">
                <FileText className="w-6 h-6" />
              </div>
              <div className="space-y-1">
                <div className="flex items-center gap-2">
                  <h3 className="font-bold text-white text-sm">{report.title}</h3>
                  <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-400 border border-emerald-500/30">
                    {report.status}
                  </span>
                </div>
                <p className="text-xs text-slate-300 leading-relaxed max-w-2xl">{report.summary}</p>
                <div className="flex items-center gap-3 text-[11px] text-slate-400 pt-1 font-medium">
                  <span className="px-2 py-0.5 rounded bg-slate-800 border border-slate-700 text-slate-300">
                    {report.report_type}
                  </span>
                  <span>•</span>
                  <span>Created: {report.created_at}</span>
                  <span>•</span>
                  <span>Author: {report.generated_by}</span>
                </div>
              </div>
            </div>

            <div className="flex items-center gap-2 self-end sm:self-center">
              <button
                onClick={() => {
                  setSelectedReport(report);
                  setIsViewModalOpen(true);
                }}
                className="px-3.5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 border border-slate-700 text-slate-300 hover:text-white text-xs font-semibold transition-colors"
              >
                View Summary
              </button>
              <button
                onClick={() => handleDownloadDemo(report)}
                className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-600 text-white text-xs font-bold shadow-lg shadow-emerald-500/25 transition-all"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Export PDF</span>
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* GENERATE MODAL */}
      <Modal
        isOpen={isGenerateModalOpen}
        onClose={() => setIsGenerateModalOpen(false)}
        title="Generate New Quality & Compliance Report"
      >
        <form onSubmit={handleGenerate} className="space-y-4">
          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-slate-300 mb-1">
              Report Type
            </label>
            <select
              value={formType}
              onChange={(e) => setFormType(e.target.value)}
              className="w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-emerald-500"
            >
              {REPORT_TYPES.filter((t) => t !== "All").map((t) => (
                <option key={t} value={t}>
                  {t}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-slate-300 mb-1">
              Report Title
            </label>
            <input
              type="text"
              required
              value={formTitle}
              onChange={(e) => setFormTitle(e.target.value)}
              className="w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-emerald-500"
            />
          </div>

          <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-800">
            <button
              type="button"
              onClick={() => setIsGenerateModalOpen(false)}
              className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-xs font-semibold text-slate-300"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="px-4 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-600 text-xs font-bold text-white shadow"
            >
              Generate Now
            </button>
          </div>
        </form>
      </Modal>

      {/* VIEW MODAL */}
      <Modal
        isOpen={isViewModalOpen}
        onClose={() => setIsViewModalOpen(false)}
        title={selectedReport?.title || "Report Overview"}
      >
        <div className="space-y-4 text-xs text-slate-300">
          <div className="p-3.5 rounded-xl bg-slate-800/60 border border-slate-700/60 space-y-1">
            <p className="font-semibold text-white">Executive Summary:</p>
            <p className="leading-relaxed">{selectedReport?.summary}</p>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-900 border border-slate-800 space-y-2 font-mono text-[11px]">
            <p className="font-bold text-slate-400 uppercase text-[10px]">Data Payload:</p>
            <pre className="text-emerald-400 overflow-x-auto">
              {JSON.stringify(selectedReport?.data, null, 2)}
            </pre>
          </div>

          <div className="flex items-center justify-end gap-3 pt-3 border-t border-slate-800">
            <button
              onClick={() => setIsViewModalOpen(false)}
              className="px-4 py-2 rounded-xl bg-slate-800 text-xs font-semibold text-slate-300"
            >
              Close
            </button>
            <button
              onClick={() => {
                handleDownloadDemo(selectedReport);
                setIsViewModalOpen(false);
              }}
              className="px-4 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-600 text-white text-xs font-bold flex items-center gap-1.5"
            >
              <Download className="w-3.5 h-3.5" /> Download Report
            </button>
          </div>
        </div>
      </Modal>
    </div>
  );
};
