"""XLSX report writer (openpyxl).

Produces one sheet per table plus a summary sheet, with native Excel charts so
the numbers stay live rather than being flattened into an image.
"""

from __future__ import annotations

import io
import re

from openpyxl import Workbook
from openpyxl.chart import BarChart, LineChart, Reference
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.worksheet import Worksheet

from app.config import settings
from app.reports.builders import ReportData

HEADER_FILL = PatternFill("solid", fgColor="15803D")
HEADER_FONT = Font(bold=True, color="FFFFFF", size=10)
TITLE_FONT = Font(bold=True, size=14, color="14532D")
SUBTITLE_FONT = Font(size=10, color="6B7280")
LABEL_FONT = Font(bold=True, size=9, color="374151")
NOTE_FONT = Font(italic=True, size=9, color="B45309")
BAND_FILL = PatternFill("solid", fgColor="F9FAFB")
THIN = Side(style="thin", color="E5E7EB")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

_INVALID_SHEET = re.compile(r"[\\/*?:\[\]]")


def _sheet_name(name: str, used: set[str]) -> str:
    """Excel sheet names: max 31 chars, no []:*?/\\, must be unique."""
    cleaned = _INVALID_SHEET.sub("-", name).strip() or "Sheet"
    cleaned = cleaned[:31]
    candidate = cleaned
    suffix = 1
    while candidate.lower() in used:
        suffix += 1
        tail = f" ({suffix})"
        candidate = cleaned[: 31 - len(tail)] + tail
    used.add(candidate.lower())
    return candidate


def _autosize(sheet: Worksheet, columns: int, *, start_row: int = 1, max_width: int = 46) -> None:
    for col_index in range(1, columns + 1):
        letter = get_column_letter(col_index)
        longest = 0
        for row in sheet.iter_rows(
            min_row=start_row, min_col=col_index, max_col=col_index, values_only=True
        ):
            value = row[0]
            if value is not None:
                longest = max(longest, len(str(value)))
        sheet.column_dimensions[letter].width = min(max_width, max(10, longest + 2))


def _write_summary(workbook: Workbook, data: ReportData) -> Worksheet:
    sheet = workbook.active
    sheet.title = "Summary"

    sheet["A1"] = data.title
    sheet["A1"].font = TITLE_FONT
    sheet["A2"] = data.subtitle
    sheet["A2"].font = SUBTITLE_FONT

    row = 4
    meta = [
        ("Organisation", settings.REPORT_ORGANISATION),
        ("Report type", str(data.report_type)),
        ("Generated at", data.generated_at.strftime("%Y-%m-%d %H:%M UTC")),
        ("Generated by", data.generated_by),
        (
            "Filters",
            ", ".join(f"{k}={v}" for k, v in data.filters.items()) or "none (all records)",
        ),
    ]
    for label, value in meta:
        sheet.cell(row=row, column=1, value=label).font = LABEL_FONT
        sheet.cell(row=row, column=2, value=str(value))
        row += 1

    row += 1
    sheet.cell(row=row, column=1, value="Key metrics").font = Font(bold=True, size=11)
    row += 1
    header_row = row
    for col, title in enumerate(("Metric", "Value"), start=1):
        cell = sheet.cell(row=header_row, column=col, value=title)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.border = BORDER
    row += 1

    for key, value in data.summary.items():
        if value is None:
            continue
        sheet.cell(row=row, column=1, value=str(key)).border = BORDER
        value_cell = sheet.cell(row=row, column=2, value=value)
        value_cell.border = BORDER
        value_cell.font = Font(bold=True)
        row += 1

    if data.notes:
        row += 1
        sheet.cell(row=row, column=1, value="Notes and limitations").font = Font(
            bold=True, size=11
        )
        row += 1
        for note in data.notes:
            cell = sheet.cell(row=row, column=1, value=note)
            cell.font = NOTE_FONT
            cell.alignment = Alignment(wrap_text=True, vertical="top")
            sheet.merge_cells(start_row=row, start_column=1, end_row=row, end_column=8)
            sheet.row_dimensions[row].height = 30
            row += 1

    sheet.column_dimensions["A"].width = 32
    sheet.column_dimensions["B"].width = 46
    sheet.freeze_panes = "A4"
    return sheet


def _write_table(workbook: Workbook, table, used_names: set[str]) -> None:
    sheet = workbook.create_sheet(_sheet_name(table.title, used_names))

    sheet.cell(row=1, column=1, value=table.title).font = TITLE_FONT
    start = 3
    if table.note:
        sheet.cell(row=2, column=1, value=table.note).font = SUBTITLE_FONT

    for col, name in enumerate(table.columns, start=1):
        cell = sheet.cell(row=start, column=col, value=name)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.border = BORDER
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

    for row_offset, row_values in enumerate(table.rows, start=start + 1):
        for col, value in enumerate(row_values, start=1):
            cell = sheet.cell(row=row_offset, column=col, value=value)
            cell.border = BORDER
            if row_offset % 2 == 0:
                cell.fill = BAND_FILL

    if not table.rows:
        sheet.cell(
            row=start + 1, column=1, value="No matching records for the selected filters."
        ).font = SUBTITLE_FONT

    sheet.freeze_panes = sheet.cell(row=start + 1, column=1)
    if table.rows:
        sheet.auto_filter.ref = (
            f"A{start}:{get_column_letter(len(table.columns))}{start + len(table.rows)}"
        )
    _autosize(sheet, len(table.columns), start_row=start)


def _write_charts(workbook: Workbook, data: ReportData, used_names: set[str]) -> None:
    if not data.charts:
        return
    sheet = workbook.create_sheet(_sheet_name("Charts", used_names))
    anchor_row = 1

    for index, series in enumerate(data.charts):
        if not series.labels or not series.values:
            continue
        # Data block for this series (kept to the left, charts anchored right).
        data_col = 1 + index * 3
        sheet.cell(row=anchor_row, column=data_col, value=series.title).font = LABEL_FONT
        header_row = anchor_row + 1
        sheet.cell(row=header_row, column=data_col, value="Label").font = HEADER_FONT
        sheet.cell(row=header_row, column=data_col).fill = HEADER_FILL
        sheet.cell(row=header_row, column=data_col + 1, value=series.y_label or "Value").font = HEADER_FONT
        sheet.cell(row=header_row, column=data_col + 1).fill = HEADER_FILL

        for offset, (label, value) in enumerate(
            zip(series.labels, series.values, strict=False), start=1
        ):
            sheet.cell(row=header_row + offset, column=data_col, value=str(label))
            sheet.cell(row=header_row + offset, column=data_col + 1, value=float(value))

        count = len(series.values)
        chart = LineChart() if series.kind == "line" else BarChart()
        chart.title = series.title
        chart.height = 7.5
        chart.width = 15
        if series.y_label:
            chart.y_axis.title = series.y_label
        values_ref = Reference(
            sheet, min_col=data_col + 1, min_row=header_row, max_row=header_row + count
        )
        cats_ref = Reference(
            sheet, min_col=data_col, min_row=header_row + 1, max_row=header_row + count
        )
        chart.add_data(values_ref, titles_from_data=True)
        chart.set_categories(cats_ref)
        sheet.add_chart(chart, f"{get_column_letter(10 + index * 9)}{2 + index * 2}")

        sheet.column_dimensions[get_column_letter(data_col)].width = 20
        sheet.column_dimensions[get_column_letter(data_col + 1)].width = 14


def render_xlsx(data: ReportData) -> bytes:
    """Render a `ReportData` bundle into XLSX bytes."""
    workbook = Workbook()
    used_names: set[str] = set()

    summary = _write_summary(workbook, data)
    used_names.add(summary.title.lower())

    for table in data.tables:
        _write_table(workbook, table, used_names)

    _write_charts(workbook, data, used_names)

    buffer = io.BytesIO()
    workbook.save(buffer)
    return buffer.getvalue()
